### POST /register
POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "username": "rahul",
  "password": "rahul",
  "email": "rk",
  "name": "rahulkumar"
}

###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
  "password": "rahul",
  "email": "rk"

}

###
GET http://localhost:9090/get_user_and_profile
 HTTP/1.1
Content-Type: application/json

{
  "token":"4ca0da9cfa0b2ad6f9f81175be4afca02ef8e156cf0566f98d8387dbd78a6f86"
}


###

GET http://localhost:9090/search_profile
Content-Type: application/json

